### ISSUE TITLE
Need Help using this as my final year project

### ISSUE THREAD

**Issue by Immanuelll** [TAMILVIP007/Attendance-System#3]
Please I would like to do this has my final year project,  can you teach me how to execute  it? @TAMILVIP007 @annihilatorrrr

**Comment by annihilatorrrr** [comment]
> Please I would like to do this has my final year project, can you teach me how to execute it? @TAMILVIP007 @annihilatorrrr

it's @TAMILVIP007 's project i see

**Comment by Immanuelll** [comment]
Ok thanks @annihilatorrrr I will await @TAMILVIP007 's reply

**Comment by TAMILVIP007** [comment]
> Please I would like to do this has my final year project, can you teach me how to execute it? @TAMILVIP007 @annihilatorrrr

Okie sure
